### ISSUE TITLE
DynamicTableEntityJsonSerializer - Multi Framework Targeting

### ISSUE THREAD

**Issue by oh-yeah** [endpointsystems/EPS.Extensions#2]
Would it be possible to also target netstandard2.0 in the DynamicTableEntityJsonSerializer project?  I would really like to use this package on an older project that is incompatible with Net 6.  I can submit a PR for this you're open to the change.

**Comment by oh-yeah** [comment]
Linking to PR #3

**Comment by elvogel** [comment]
merged. I'll try and push out a build tonight.
